# Generated by Django 5.0.6 on 2024-10-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('position', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('NULL', 'NULL')], max_length=5, null=True)),
                ('levels', models.IntegerField()),
                ('lft', models.IntegerField()),
                ('rgt', models.IntegerField()),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='placement.tree_structure')),
            ],
        ),
    ]
