# Generated by Django 5.1.2 on 2024-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_remove_tree_structure_id_tree_structure_binary_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_structure',
            name='capping_value',
            field=models.FloatField(default=0.0),
        ),
    ]
