# Generated by Django 5.1.2 on 2024-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_tree_structure_capping_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_structure',
            name='carry',
            field=models.FloatField(default=0.0),
        ),
    ]
