# Generated by Django 5.1.2 on 2024-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_tree_structure_carry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_structure',
            name='carry',
            field=models.IntegerField(),
        ),
    ]
