# Generated by Django 5.0.6 on 2024-10-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(help_text='Total members in the binary tree.', verbose_name='Total Members')),
                ('levels', models.IntegerField(help_text='Number of levels in the binary tree.', verbose_name='Number of Levels')),
            ],
        ),
        migrations.CreateModel(
            name='Compensations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_bonus_percent', models.FloatField(help_text='Sponsor bonus percentage.', verbose_name='Sponsor Bonus (%)')),
                ('binary_pairs', models.IntegerField(help_text='Number of binary pairs.', verbose_name='Binary Pairs')),
                ('binary_bonus_percent', models.FloatField(help_text='Binary bonus percentage.', verbose_name='Binary Bonus (%)')),
                ('matching_bonus_percent', models.FloatField(help_text='Matching bonus percentage.', verbose_name='Matching Bonus (%)')),
                ('matching_bonus_levels', models.IntegerField(help_text='Number of levels for matching bonus.', verbose_name='Matching Bonus Levels')),
                ('cap_limit', models.FloatField(help_text='Maximum payout limit.', verbose_name='Capping Limit')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10, verbose_name='Base Currency')),
                ('joining_package_fee', models.FloatField(help_text='Fee for joining the package.', verbose_name='Joining Package Fee')),
                ('additional_product_price', models.FloatField(help_text='Additional price for the product.', verbose_name='Additional Product Price')),
            ],
        ),
    ]
