# Generated by Django 5.0.6 on 2024-11-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensations',
            name='bonus_type',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='levels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='total_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='binary_pairs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='cap_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_levels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='matching_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compensations',
            name='sponsor_bonus_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='additional_product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='joining_package_fee',
            field=models.FloatField(),
        ),
    ]
